### PR TITLE
Fix card and format list

### LINKED ISSUE #132: UI: improve task card presentation
A better presentation of the Task card could be:

```
1. 25 packs of chicken wings
Assigned: 2pm - 4pm @ Aloysius Chan (#1) - 81327123
Deliver To: Alex Yeoh (#1) - 97438807
Address: (NO CHANGE)
Date: (NO CHANGE)
```
To utilize horizontal space and present the information more clearly.

### LINKED ISSUE #133: UI: improve Driver card presentation
IMO, you don't need to show a driver's Address and Email in the driver card. Just show name, phone, and availability. Additional information can be displayed via the `read` command and show in the error message response box.

### LINKED ISSUE #134: UI: Ongoing and Incomplete section doesn't show the current Task ID
Both has Task ID 1? This disables any task related operations.
Screenshot 2019-10-30 at 12 38 01 PM

### PR DESCRIPTION
**Pull request by ArgVampir**
close #132 
close #133 
close #134 

For the ID it is currently displayed at the bottom. But if you want to reduce the description length and can move it next to the heading of each task. Doing so the list will not be consecutively ordered from 1 to ... in naming. Let me know your preference!

### CODE REVIEW

**Comment by junnbang** [comment]
I think there's no need to add the Assigned part under Incomplete Delivery Task, since all of them are unassigned

**Comment by ArgVampir** [comment]
> I think there's no need to add the Assigned part under Incomplete Delivery Task, since all of them are unassigned
Agree will remove

**Comment by ArgVampir** [comment]
Screen Shot 2562-10-31 at 00 30 53

How is this layout? Up to three clear boxes. I feel `Assigned:` and `Deliver to:` is also quite important and should be kept.

**Comment by junnbang** [comment]
> Screen Shot 2562-10-31 at 00 30 53
> 
> How is this layout? Up to three clear boxes. I feel `Assigned:` and `Deliver to:` is also quite important and should be kept.

I think it looks better. i agree the `assigned` and `deliver to` for Ongoing task is important enough to keep.

but see how you can minimize the details displayed. Like for eg. customer. If the task list already shows the address of the customer, then is the address field displayed under the customer list still essential? things like that.

Also can put your creativity on the css part, which is the colors and design of the layout

Great work!

**Pull request merged**
